name: unstructured

channels:
  - defaults
  - anaconda
  - conda-forge
  - pytorch

dependencies:
  - python=3.10
  - pytorch=2.1.2
  - pywin32
  - poppler
  - torchvision
  - pip
  - pip:
    - fastapi
    - uvicorn
    - huggingface-hub
    - layoutparser
    - black
